import { describe, it, expect } from "vitest";
import {
  sign,
  verify,
  nowSeconds,
  SIGNATURE_HEADER,
  TIMESTAMP_HEADER,
  SIGNATURE_PREFIX,
  TOLERANCE_SECONDS,
} from "../src/auth/hmac.ts";

const SECRET = "shared-secret-for-parity-test";
const BODY = '{"job_id":"3f7c1e2a","repo":"org/app"}';

/** Unix seconds, as a decimal string — the format the caller sends. */
const ts = (offsetSeconds = 0) => String(Math.floor(Date.now() / 1000) + offsetSeconds);

const headersOf = (h: Record<string, string>) => ({
  signature: h[SIGNATURE_HEADER],
  timestamp: h[TIMESTAMP_HEADER],
});

describe("parity with the caller's PHP implementation", () => {
  /**
   * Generated by PHP, the same call Bilis's VerifyAyosSignature makes:
   *
   *   hash_hmac('sha256', $body, $secret)
   *
   * If this vector ever fails, Ayos and the caller have diverged and every
   * request between them will 401 — which is exactly the bug this pins.
   */
  it("matches a signature produced by PHP hash_hmac over the raw body", () => {
    const expected = "sha256=9a6c03acb39abd5e4b6ccbb33a7cd1bbe1ce26ba3a6e0b1d1b8f56590c4fa268";
    expect(sign(SECRET, BODY, ts())[SIGNATURE_HEADER]).toBe(expected);
  });

  it("accepts that signature with a Unix-seconds timestamp", () => {
    expect(
      verify(SECRET, BODY, {
        signature: "sha256=9a6c03acb39abd5e4b6ccbb33a7cd1bbe1ce26ba3a6e0b1d1b8f56590c4fa268",
        timestamp: ts(),
      }),
    ).toEqual({ ok: true });
  });

  it("signs the body ALONE — the timestamp is not part of the mac", () => {
    // Deliberate: this documents the scheme rather than endorsing it. See the
    // replay note in SPEC.md.
    const a = sign(SECRET, BODY, "1700000000")[SIGNATURE_HEADER];
    const b = sign(SECRET, BODY, "1900000000")[SIGNATURE_HEADER];
    expect(a).toBe(b);
  });

  it("rejects an ISO-8601 timestamp, which the caller never sends", () => {
    const h = sign(SECRET, BODY);
    expect(
      verify(SECRET, BODY, { signature: h[SIGNATURE_HEADER], timestamp: new Date().toISOString() }),
    ).toEqual({ ok: false, reason: "malformed timestamp" });
  });
});

describe("sign", () => {
  it("defaults the timestamp to now, in Unix seconds", () => {
    const h = sign(SECRET, BODY);
    expect(h[TIMESTAMP_HEADER]!).toMatch(/^\d+$/);
    expect(Math.abs(Number(h[TIMESTAMP_HEADER]) - Number(nowSeconds()))).toBeLessThanOrEqual(1);
  });

  it("prefixes the digest with the algorithm", () => {
    expect(sign(SECRET, BODY)[SIGNATURE_HEADER]!.startsWith(SIGNATURE_PREFIX)).toBe(true);
  });
});

describe("verify", () => {
  it("round-trips a freshly signed body", () => {
    expect(verify(SECRET, BODY, headersOf(sign(SECRET, BODY)))).toEqual({ ok: true });
  });

  it("verifies an empty body", () => {
    expect(verify(SECRET, "", headersOf(sign(SECRET, "")))).toEqual({ ok: true });
  });

  it("rejects a tampered body", () => {
    const h = sign(SECRET, BODY);
    expect(verify(SECRET, `${BODY} `, headersOf(h))).toEqual({
      ok: false,
      reason: "signature mismatch",
    });
  });

  it("rejects a signature made with a different secret", () => {
    expect(verify(SECRET, BODY, headersOf(sign("other-secret", BODY)))).toEqual({
      ok: false,
      reason: "signature mismatch",
    });
  });

  it("accepts timestamps at both edges of the window", () => {
    const h = sign(SECRET, BODY);
    for (const offset of [-TOLERANCE_SECONDS, TOLERANCE_SECONDS]) {
      expect(
        verify(SECRET, BODY, { signature: h[SIGNATURE_HEADER], timestamp: ts(offset) }),
      ).toEqual({ ok: true });
    }
  });

  it("rejects a timestamp outside the window in either direction", () => {
    const h = sign(SECRET, BODY);
    for (const offset of [-(TOLERANCE_SECONDS + 2), TOLERANCE_SECONDS + 2]) {
      expect(
        verify(SECRET, BODY, { signature: h[SIGNATURE_HEADER], timestamp: ts(offset) }),
      ).toEqual({ ok: false, reason: "timestamp outside window" });
    }
  });

  it("checks the window before the mac, so a stale-but-valid signature still fails", () => {
    const h = sign(SECRET, BODY, "1000000000");
    expect(verify(SECRET, BODY, headersOf(h))).toEqual({
      ok: false,
      reason: "timestamp outside window",
    });
  });

  it("rejects missing headers", () => {
    expect(verify(SECRET, BODY, { timestamp: ts() })).toEqual({
      ok: false,
      reason: "missing signature",
    });
    expect(verify(SECRET, BODY, { signature: sign(SECRET, BODY)[SIGNATURE_HEADER] })).toEqual({
      ok: false,
      reason: "missing timestamp",
    });
    expect(verify(SECRET, BODY, {})).toEqual({ ok: false, reason: "missing signature" });
  });

  it("rejects a signature without the sha256= prefix", () => {
    const raw = sign(SECRET, BODY)[SIGNATURE_HEADER]!.slice(SIGNATURE_PREFIX.length);
    expect(verify(SECRET, BODY, { signature: raw, timestamp: ts() })).toEqual({
      ok: false,
      reason: "malformed signature",
    });
  });

  it("does not throw on a non-hex or wrong-length signature", () => {
    for (const sig of ["sha256=zzzz", "sha256=", "sha256=abcd"]) {
      const result = verify(SECRET, BODY, { signature: sig, timestamp: ts() });
      expect(result.ok).toBe(false);
    }
  });

  it("tolerates surrounding whitespace, as a header round-trip can introduce", () => {
    const h = sign(SECRET, BODY);
    expect(
      verify(SECRET, BODY, {
        signature: ` ${h[SIGNATURE_HEADER]} `,
        timestamp: ` ${h[TIMESTAMP_HEADER]} `,
      }),
    ).toEqual({ ok: true });
  });
});
